language: node_js
node_js:
  - 'lts/*'
  - '8'
  - '10'
  - '12'
sudo: false
cache: yarn
before_install:
  - npm install --global nyc
script:
  - yarn build
  - yarn test-coverage
  - nyc yarn test
after_script:
  - npm install --global codecov coveralls
  - nyc report --reporter=text-lcov | coveralls
  - cat ./coverage/lcov.info | codecov
