language: node_js
node_js:
  - 'lts/*'
sudo: false
cache: yarn
before_install:
  - npm install --global nyc
script:
  - npm run build
  - npm run test-coverage
after_script:
  - npm install --global codecov coveralls
  - nyc report --reporter=text-lcov | coveralls
  - cat ./coverage/lcov.info | codecov
