language: node_js
node_js:
  - 'lts/*'
sudo: false
cache: yarn
before_install:
  - npm install --global nyc
script:
  - npm run build
  - nyc npm run test
after_script:
  - npm install --global codecov coveralls
  - cat ./coverage/lcov.info | coveralls
  - cat ./coverage/lcov.info | codecov
